version: "3"

services:
  tile-nextjs:
    container_name: tile-nextjs-container
    image: tile-nextjs-img
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5100:3000
    env_file:
      - .env
